#!/usr/bin/env bash
#script to make server run commands as nginx user
# Stop nginx if it's already running
sudo systemctl stop nginx

# Change user and group ownership of nginx directories
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx

sudo chmod -R 755 /etc/nginx/
sudo pkill -9 apache2
sudo sed -i ' s/8080/8081/g ' /etc/apache2/ports.conf
redémarrage du service sudo apache2
su nginx -c " sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default "
redémarrage du service nginx su nginx
