#!/usr/bin/env bash
# bash script that installs HAProxy & makes configurations to meet the following requirements:
sudo service haproxy stop
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5517-web
    bind *:80
    mode http
    balance roundrobin
    server 5431-web-01 54.227.64.217:80 check
    server 5431-web-02 54.146.238.187:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart