#!/usr/bin/env bash
#bash script to make sure our nginx is listen on port 80 on all ipv4 ips
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill  " $( pgrep ' nginx '  | head -1 ) "
