#!/usr/bin/env bash
#script to send files to server. 4 params.
#check number of parameters
if [ $# -ne 4]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
#params an shit
PATH_TO_FILE = "$1"
IP = "$2"
USERNAME = "$3"
PATH_TO_SSH_KEY = "$4"

 scp -0 "StrictHostKeyChecking no" -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"