#!/usr/bin/env bash
#script that sets up nginx server
#!/usr/bin/env bash

#!/usr/bin/env bash
#script that sets up nginx server

sudo apt-get update
sudo apt-get install nginx -y

sudo mkdir /var/www/html

sudo touch /var/www/html/index.html

sudo sh -c 'echo "<html><h1>Holberton School</h1></html>" > /var/www/html/index.html'

sudo sh -c 'printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /var/www/html;
    index       index.html index.htm;
}
" > /etc/nginx/sites-available/default'

sudo service nginx restart
