#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update -y
sudo apt-get install -y nginx
#sudo ufw allow 'Nginx HTTP'
config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
		    
	location /redirect_me {
		return 301 https://www.youtube.com
"
sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "Holberton School" > /var/www/html/index.html
echo "$config" > /etc/nginx/sites-available/default
sudo service nginx restart