#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:

sudo apt-get update
sudo echo "Holberton School" > /etc/nginx/html/index.html
sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;

     location /redirect_me {
        return 301 http://google.com/;
    }
}
" > /etc/nginx/sites-available/default


sudo service nginx restart