#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/mutabazi

touch /etc/nginx/mutabazi/index.html


echo "Mutabazi & Holberton School" > /etc/nginx/mutabazi/index.html

# Create custom 404 error page
echo "<!DOCTYPE html>
<html>
<head>
  <title>Mutabazi</title>
</head>
<body>
  <h1>404 Not Found</h1>
  <p>Ceci n'est pas une page</p>
</body>
</html>" | sudo tee /var/www/mutabazi/404.html >/dev/null

printf %s "http{
    types {
        text/css        css;
        text/html       html:
        text/js         js;   
    }

    server {
        listen  80;
        root /var/www/mutabazi;
        location /redirect_me{
          return 301 https://www.google.com
        }
    }
}

events {

}
" > /etc/nginx/nginx.conf

service nginx restart
