#!/usr/bin/env bash
# bash script to install nginx web server & make the following configurations:

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html

sudo touch /etc/nginx/html/index.html


sudo echo "Holberton School" > /etc/nginx/html/index.html

# Create custom 404 error page
sudo echo "<!DOCTYPE html>
<html>
<head>
  <title>404 Not Found</title>
</head>
<body>
  <h1>404 Not Found</h1>
  <p>Ceci n'est pas une page</p>
</body>
</html>" | sudo tee /var/www/html/404.html >/dev/null

sudo printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
     error_page 404 /404.html;
     location /404 {
        root /etc/nginx/html;
        internal;
     }
}
" > /etc/nginx/sites-available/default

sudo service nginx restart